'use strict';

const path = require('path');
const fs = require('fs');
const { writeManifest, createEmptyManifest, MANIFEST_PATH } = require('../lib/manifest');

const GITIGNORE_BLOCK = [
  '# claude-skills-cli: generated by `skills install`, do not commit',
  '.claude/skills/**',
].join('\n');

function ensureGitignoreEntry(projectRoot) {
  const gitignorePath = path.join(projectRoot, '.gitignore');
  let existing = '';
  if (fs.existsSync(gitignorePath)) {
    existing = fs.readFileSync(gitignorePath, 'utf8');
  }

  const lines = existing.split(/\r?\n/);
  const alreadyIgnored = lines.some((line) => {
    const t = line.trim();
    return (
      t === '.claude/skills/**' ||
      t === '.claude/skills/' ||
      t === '.claude/skills' ||
      t === '.claude/skills/*.md' // legacy v1.x entry; still covers our needs
    );
  });

  if (alreadyIgnored) {
    return { changed: false, action: 'skipped (already ignored)' };
  }

  let prefix;
  if (existing.length === 0) {
    prefix = '';
  } else if (existing.endsWith('\n\n') || existing.endsWith('\n')) {
    prefix = existing.endsWith('\n\n') ? '' : '\n';
  } else {
    prefix = '\n\n';
  }
  fs.writeFileSync(gitignorePath, existing + prefix + GITIGNORE_BLOCK + '\n', 'utf8');
  return { changed: true, action: 'updated' };
}

async function initCommand(projectRoot) {
  const manifestPath = path.join(projectRoot, MANIFEST_PATH);

  let manifestAction;
  if (fs.existsSync(manifestPath)) {
    manifestAction = 'skipped (already exists)';
  } else {
    writeManifest(projectRoot, createEmptyManifest());
    manifestAction = 'created';
  }

  const gitignoreResult = ensureGitignoreEntry(projectRoot);

  console.log(`${MANIFEST_PATH}: ${manifestAction}`);
  console.log(`.gitignore: ${gitignoreResult.action}`);
  console.log('');
  console.log('Next:  skills skill add <source> --skill <name> --version <tag>');
}

module.exports = { initCommand };
